"""Single A2A seller agent entrypoint. Generated by `bag recipe code agent`.

This is the VALUABLE agent AND the SOLE key-holder/signer. It serves its two
ERC-8183 seller skills DIRECTLY over the A2A protocol on AWS Bedrock AgentCore
(``--protocol A2A``): AgentCore's ``serve_a2a`` wraps the official ``a2a-sdk`` and
exposes the agent card at ``/.well-known/agent-card.json`` + JSON-RPC
``message/send`` on ``0.0.0.0:9000`` (``AGENT_PORT`` overrides locally). There
is no separate forwarding service — the
agent IS the seller (see executor.py + agent_card.py).

A2A skills (executor.py):

    negotiate     → read the FIXED list price → CLAMP to [min,max] → EIP-191 SIGN
                    the offer (no LLM, no tools) → return the signed offer (or reject)
    notify_funded → re-verify the funded job on-chain (fast) → ACK accepted at once,
                    then in the BACKGROUND: LLM work → manifest → storage →
                    submit_result (SIGN + broadcast). The buyer polls the chain for
                    the deliverable. Each notify also sweeps other FUNDED jobs
                    (buyer-push fallback). While background work is in flight the
                    ``ping_handler`` reports HEALTHY_BUSY so AgentCore keeps the
                    scale-to-zero runtime warm until it lands.

Buyers reach this endpoint with an OAuth2 (Cognito) bearer — AgentCore A2A
mandates inbound auth (see agent_card.py + ``bag deploy provision-cognito``).

## Boundaries (do NOT cross — they are the whole point)

- The agent does ALL deterministic SIGNING (quote-sign + submit + settle +
  automatic x402 LLM-credit auto-renew). ALL signing is FIXED code in
  ``signing.py`` — NEVER an LLM-callable tool (money never in the LLM).
- The price is a FIXED list price from studio.toml (clamped before signing) —
  the LLM never prices; it only PRODUCES the work text in ``fulfill``.
- Chain access for the LLM is READ-ONLY tools only (``tools.py``).
- ``settle`` (claim payment after the dispute window) is operator-driven — run
  ``bag erc8183 settle <job_id>``; it is deliberately NOT an A2A skill.
"""
from __future__ import annotations

import json
import logging
import os
import re
import sys
from typing import AsyncGenerator

from google.adk.agents import Agent
from google.adk.runners import InMemoryRunner
from google.genai import types as gtypes

from managed_model import build_model
from bnbagent_studio_core.wallet import (
    ensure_keystore_materialized,
    ensure_twak_materialized,
)

from agent_card import build_agent_card
from executor import SellerAgentExecutor
from report_schema import StockReport
from report_renderer import render_report
from tools import LLM_READ_TOOLS

APP_NAME = "agent"


# --- Logging -------------------------------------------------------------------
# Make the agent's own logs visible in `docker logs` / CloudWatch — ESPECIALLY
# the BACKGROUND notify_funded delivery, which runs AFTER the A2A ack (off the
# request path). Without this the "seller-agent.*" loggers inherit the root
# config (which opentelemetry / AgentCore may leave at WARNING or route away),
# so a delivery that fails — e.g. a missing STORAGE_API_URL at the IPFS-pin step
# — vanishes silently while the buyer polls the chain forever. We attach our own
# stdout handler at INFO so success AND failure are always on stdout.
def _configure_logging() -> None:
    log = logging.getLogger("seller-agent")
    if log.handlers:  # idempotent (cold start may re-import)
        return
    handler = logging.StreamHandler(sys.stdout)
    handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(name)s: %(message)s"))
    log.addHandler(handler)
    log.setLevel(logging.INFO)
    log.propagate = False  # don't double-log via the root handler


_configure_logging()


def _generator_tag() -> str:
    """Deliverable ``generator`` label: this seller's own name, read from
    studio.toml ``[project].name`` (minus the ``-agent`` suffix) so each
    delivered manifest is self-identifying. Best-effort — falls back to
    ``APP_NAME`` if the config can't be read."""
    try:
        from bnbagent_studio_core import config

        name = str(((config.load_studio_toml() or {}).get("project") or {}).get("name") or "")
    except Exception:  # noqa: BLE001 — a metadata label must never break fulfill
        return APP_NAME
    return name[: -len("-agent")] if name.endswith("-agent") else (name or APP_NAME)


GENERATOR = _generator_tag()


# --- Runtime secrets -----------------------------------------------------------
# Keep plaintext secrets OUT of agentcore.json. When BNBAGENT_RUNTIME_SECRET_ID is set
# (deployed runtime), pull a JSON {ENV_NAME: value} blob from AWS Secrets Manager
# into the process env BEFORE anything reads it (keystore unlock, provider key,
# build_model, Cognito OAuth env). No-op locally, where .env.local already
# populated the environment — `setdefault` never overrides an already-present var.
def _load_runtime_secrets() -> None:
    secret_id = os.environ.get("BNBAGENT_RUNTIME_SECRET_ID")
    if not secret_id:
        return
    import boto3

    resp = boto3.client("secretsmanager").get_secret_value(SecretId=secret_id)
    for key, value in json.loads(resp["SecretString"]).items():
        os.environ.setdefault(key, str(value))


_load_runtime_secrets()

# --- Paymaster patch -----------------------------------------------------------
# MegaFuel paymaster (bsc-testnet default) accepts transactions but never
# confirms them on testnet — every submit_result call would silently fail.
# Patch both the config module AND the already-bound name in bnbagent.erc8183.client
# (which imported resolve_network at module level), then clear the LRU cache so
# get_8183_client() rebuilds with use_paymaster=False.
import dataclasses as _dc
import bnbagent.config as _bnbagent_cfg
import bnbagent.erc8183.client as _bnb_erc8183_client

_orig_resolve = _bnbagent_cfg.resolve_network


def _resolve_no_paymaster(network="bsc-testnet", **kw):
    nc = _orig_resolve(network, **kw)
    return _dc.replace(nc, use_paymaster=False)


_bnbagent_cfg.resolve_network = _resolve_no_paymaster
_bnb_erc8183_client.resolve_network = _resolve_no_paymaster

try:
    from bnbagent_studio_core.erc8183.client import _reset_cache as _reset_8183_cache
    _reset_8183_cache()
except Exception:
    pass

# --- Wallet bootstrap -----------------------------------------------------------
# Wallet material is NEVER bundled into the deploy artifact. `bag deploy`
# injects it via Secrets Manager and these calls (run once at cold start,
# before any signing) materialize it on disk. Each is a no-op for the other
# wallet kind and locally, where the wallet already lives on disk:
#  - evm-local: WALLET_KEYSTORE_JSON → keystore file (unlocked with WALLET_PASSWORD)
#  - twak:      TWAK_WALLET_JSON / TWAK_CREDENTIALS_JSON → $TMPDIR/twak-home/.twak
#               (exported as TWAK_HOME_DIR; twak reads TWAK_WALLET_PASSWORD itself)
ensure_keystore_materialized()
ensure_twak_materialized()

# --- Agent + runtime ----------------------------------------------------------
# LLM credit auto-renew (Pieverse path): `build_model()` (in managed_model.py)
# returns a managed model wrapper that auto-tops up the active Pieverse key
# before each generate call when [llm.auto_renew] is enabled. That top-up is
# the ONLY automatic signing path outside signing.py — it is budget-gated and
# is NOT an LLM tool. It rides transparently into `fulfill`.
#
# trap: Agent.name must be a valid Python identifier — no hyphens. ADK silently
# misbehaves on names containing "-".
#
# The LLM runs ONLY in `fulfill` (the value hook). `negotiate` is rule-based and
# never touches the LLM. The read-only chain tools are attached so the work can
# read on-chain context if it needs to — drop them from `tools.py` if your work
# doesn't read chain. Signing / settle are NEVER tools — they are fixed code in
# signing.py, triggered by the A2A skills, never callable by the LLM. (The one
# deliberate exception: the x402-buyer recipe's PAID fetch tools — see the
# `tools=` note below — the LLM picks the URL, but who gets paid and the
# per-call/daily caps stay locked in studio.toml.)
_model = build_model()  # managed model with the auto-renew hook (fulfill only)

agent = Agent(
    name="seller_agent",
    model=_model,
    instruction=(
        "You are a professional buy-side portfolio analyst. A client has paid for a premium, actionable report.\n\n"
        "STAGE 1 — DATA COLLECTION (call ALL tools before writing anything):\n"
        "For EACH symbol call in order:\n"
        "  1. get_stock_quote(symbol)       — price, PE, PB, PEG, beta, analyst target\n"
        "  2. get_technical_signals(symbol) — RSI-14, weekly RSI, MACD, Bollinger, MA50/200, ADX, OBV, ATR, VaR\n"
        "  3. get_options_sentiment(symbol) — put/call ratio, implied volatility\n"
        "  4. get_insider_activity(symbol)  — SEC Form 4 insider filing count\n"
        "  5. get_news_sentiment(symbol)    — AI sentiment score + recent headlines\n"
        "Call once: get_macro_context() — VIX, Fed rate, 10Y yield, CPI, unemployment\n\n"
        "NEVER fabricate numbers. Use ONLY data returned by tool calls.\n\n"
        "STAGE 2 — WRITE A SCANNABLE, ACTIONABLE REPORT:\n"
        "Use tables for data, direct language, no padding. Every sentence must add value.\n"
        "Sections required:\n"
        "  1. Market Snapshot — macro table + one-line risk-on/off verdict\n"
        "  2. Per-stock analysis — verdict banner, fundamentals table, technical signals table,\n"
        "     bull/bear thesis, sentiment signals, portfolio P&L (if client holds), recommendation\n"
        "  3. Portfolio Rebalancing Plan — current allocation table, specific TRIM/ADD/HOLD actions\n"
        "     with share counts and rationale; if recommending a new BUY, name which holding to trim\n"
        "  4. Watchlist: Related Stocks — 3-5 sector peers or thematic names worth monitoring,\n"
        "     using your market knowledge; include entry zone and catalyst\n"
        "  5. Risk Dashboard — concentration, rate sensitivity, correlation in a table\n"
        "  6. Disclaimer\n\n"
        "If a symbol returns an error, note it briefly and continue with the remaining symbols."
    ),
    # LLM_READ_TOOLS = read-only chain tools (wallet, balances, ERC-8004/8183
    # queries). Edit `tools.py` to add/remove. These are READ-ONLY — the agent
    # never signs via a tool; all signing is in signing.py (fixed code).
    # To let the agent BUY paid data at work time (e.g. CMC market data after
    # `bag x402 trust cmc` + `bag recipe code x402-buyer`), append the emitted
    # tool set — payee + per-call/daily caps stay locked in studio.toml:
    #   from x402_buyer import x402_buyer_set
    #   tools=[*LLM_READ_TOOLS, *x402_buyer_set],
    tools=LLM_READ_TOOLS,
)
runner = InMemoryRunner(agent=agent, app_name=APP_NAME)


# --- JSON extraction helper ---------------------------------------------------

def _extract_json(text: str) -> str:
    """Extract the outermost JSON object from LLM text.

    Handles: pure JSON, JSON in ```json fences, JSON with a prose preamble.
    Raises ValueError when no valid JSON object boundary is found.
    """
    stripped = text.strip()
    # Fast path: already bare JSON
    if stripped.startswith("{"):
        return stripped
    # Strip code fences (```json ... ``` or ``` ... ```)
    fence = re.search(r"```(?:json)?\s*(\{.*\})\s*```", stripped, re.DOTALL)
    if fence:
        return fence.group(1)
    # Find outermost { ... } by brace counting
    start = text.find("{")
    if start == -1:
        raise ValueError("No JSON object found in LLM response")
    depth = 0
    for i, ch in enumerate(text[start:], start):
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise ValueError("Unmatched braces — JSON object not closed in LLM response")


# --- One-shot LLM helper (the executor's `fulfill` work hook) ------------------

_log = logging.getLogger("seller-agent")


async def _call_runner(prompt: str, session_id: str) -> str:
    """Run the ADK runner once and return raw final-response text (thought-filtered)."""
    session_service = runner.session_service
    existing = await session_service.get_session(
        app_name=runner.app_name, user_id="service", session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=runner.app_name, user_id="service", session_id=session_id
        )
    user_msg = gtypes.Content(role="user", parts=[gtypes.Part(text=prompt)])
    parts: list[str] = []
    async for event in runner.run_async(
        user_id="service", session_id=session_id, new_message=user_msg
    ):
        if event.is_final_response() and event.content:
            for p in event.content.parts:
                if p.text and not getattr(p, "thought", False):
                    parts.append(p.text)
    return "\n".join(parts).strip()


def _try_parse_report(text: str) -> StockReport | None:
    """Extract + parse + validate the StockReport JSON from LLM text. Returns None on failure."""
    try:
        json_str = _extract_json(text)
        return StockReport.model_validate_json(json_str)
    except Exception as exc:
        _log.warning("report parse/validation failed: %s", exc)
        return None


async def _run_llm(
    prompt: str,
    *,
    session_id: str,
    symbols: list[str] | None = None,
) -> str:
    """Run the agent, parse its JSON output, validate the schema, render Markdown.

    Flow:
      1. Call the ADK runner → raw LLM text (thinking stripped).
      2. Extract the JSON object from the text.
      3. Parse + validate with StockReport (Pydantic).
      4. Check that every requested symbol has an analyses entry.
      5. Render to institutional Markdown via report_renderer.
      On parse/validation failure: retry once with a correction prompt,
      then fall back to delivering the raw LLM text so the buyer always gets
      something.
    """
    raw = await _call_runner(prompt, session_id)

    report = _try_parse_report(raw)

    if report is None:
        # Retry: ask the model to fix its output in the same session
        _log.info("retrying with correction prompt (session %s)", session_id)
        correction = (
            "Your previous response could not be parsed as valid JSON matching the StockReport schema. "
            "Output ONLY the corrected JSON object — no text before or after it, no code fences. "
            "Ensure the analyses array has one entry per symbol and all required fields are present."
        )
        raw2 = await _call_runner(correction, session_id)
        report = _try_parse_report(raw2)

    if report is None:
        _log.error("structured output failed after retry (session %s); delivering raw text", session_id)
        return raw  # fall back: buyer still gets the LLM text

    # Validate symbol completeness (code-level, not prompt-level)
    if symbols:
        returned = {a.symbol.upper() for a in report.analyses}
        missing = [s for s in symbols if s.upper() not in returned]
        if missing:
            _log.warning("analyses missing for symbols %s (session %s)", missing, session_id)
            # Deliver what we have — partial is better than nothing

    return render_report(report)


async def _stream_runner(
    prompt: str,
    session_id: str,
    symbols: list[str] | None = None,
) -> AsyncGenerator[tuple[str, dict], None]:
    """Async generator for SSE streaming: yields (event_name, data) tuples.

    Used by the x402 channel (X402Handler) to push live progress events and
    the final rendered report over a single HTTP connection. Not used by the
    ERC-8183 A2A path (which delivers async via submit_result on-chain).

    Yields:
      ("progress", {"stage": "collecting", "tool": <name>, "message": ...})
      ("progress", {"stage": "generating", "message": "Rendering report..."})
      ("report",   {"content": <markdown>, "format": "markdown"})
      ("done",     {})
    """
    session_service = runner.session_service
    existing = await session_service.get_session(
        app_name=runner.app_name, user_id="service", session_id=session_id
    )
    if existing is None:
        await session_service.create_session(
            app_name=runner.app_name, user_id="service", session_id=session_id
        )

    user_msg = gtypes.Content(role="user", parts=[gtypes.Part(text=prompt)])
    parts: list[str] = []

    async for event in runner.run_async(
        user_id="service", session_id=session_id, new_message=user_msg
    ):
        if event.content:
            for part in event.content.parts:
                fn_call = getattr(part, "function_call", None)
                if fn_call:
                    tool_name = getattr(fn_call, "name", str(fn_call))
                    yield "progress", {
                        "stage": "collecting",
                        "tool": tool_name,
                        "message": f"Running {tool_name}...",
                    }
        if event.is_final_response() and event.content:
            for p in event.content.parts:
                if p.text and not getattr(p, "thought", False):
                    parts.append(p.text)

    raw = "\n".join(parts).strip()

    yield "progress", {"stage": "generating", "message": "Rendering report..."}

    report = _try_parse_report(raw)
    if report is None:
        # Fallback: deliver raw text (buyer still gets something)
        _log.warning("x402 stream: structured parse failed; delivering raw text (session %s)", session_id)
        yield "report", {"content": raw, "format": "text"}
    else:
        if symbols:
            returned = {a.symbol.upper() for a in report.analyses}
            missing = [s for s in symbols if s.upper() not in returned]
            if missing:
                _log.warning("x402 stream: missing analyses for %s (session %s)", missing, session_id)
        yield "report", {"content": render_report(report), "format": "markdown"}

    yield "done", {}


def _default_network() -> str:
    """studio.toml ``[network].default`` (best-effort; used by the funded sweep)."""
    try:
        from bnbagent_studio_core import config

        return str(((config.load_studio_toml() or {}).get("network") or {}).get("default") or "bsc-testnet")
    except Exception:  # noqa: BLE001
        return "bsc-testnet"


# --- A2A surface --------------------------------------------------------------
# The executor backs the seller skills with signing.py fixed code (NEVER an LLM
# tool). serve_a2a (AgentCore SDK, built on the official a2a-sdk) hosts the agent
# card + JSON-RPC message/send on 0.0.0.0:9000, adds GET /ping, and overwrites
# the card url with the deployed runtime URL ($AGENTCORE_RUNTIME_URL).
executor = SellerAgentExecutor(
    run_work=_run_llm, generator=GENERATOR, network=_default_network()
)
agent_card = build_agent_card()


def _ping_status():
    """GET /ping status fed to AgentCore: HEALTHY_BUSY while a background delivery
    is in flight, else HEALTHY.

    notify_funded acks immediately and runs the slow work (LLM + on-chain submit)
    in the background. Reporting HEALTHY_BUSY tells AgentCore the runtime is still
    working, so the scale-to-zero runtime is NOT reaped on idle before delivery
    lands (bounded by the session max-lifetime; ≤8h)."""
    from bedrock_agentcore.runtime.models import PingStatus

    return PingStatus.HEALTHY_BUSY if executor.is_busy() else PingStatus.HEALTHY


# --- JSON-RPC error hardening -------------------------------------------------
# a2a-sdk builds -32602 (InvalidParams) / -32600 (InvalidRequest) JSON-RPC error
# responses from a Pydantic ValidationError, and Pydantic embeds an ``input`` key
# in each error entry that echoes the caller's raw request body back to them
# (a2a/server/apps/jsonrpc/jsonrpc_app.py). It only ever reflects the CALLER'S OWN
# input to that same caller (not cross-tenant), so this is low-severity, but we
# strip ``input`` from outgoing JSON-RPC error data anyway — no reason to echo
# request bodies. This is a tiny pure-ASGI wrapper (no SDK edit) that rewrites the
# response body only for JSON-RPC error payloads; every other response passes
# through untouched.
def _strip_error_input(app):
    async def _wrapped(scope, receive, send):
        if scope["type"] != "http":
            await app(scope, receive, send)
            return

        # `buffer` is decided from the response start (content-type): we only
        # buffer+rewrite JSON bodies (the JSON-RPC error path). SSE / any other
        # response streams through unbuffered so streaming is never broken.
        state: dict = {"buffer": False, "start": None}
        chunks: list[bytes] = []

        async def _capture(message):
            if message["type"] == "http.response.start":
                ctype = dict(message.get("headers", [])).get(b"content-type", b"")
                state["buffer"] = b"application/json" in ctype.lower()
                state["start"] = message
                if not state["buffer"]:
                    await send(message)
            elif message["type"] == "http.response.body":
                if not state["buffer"]:
                    await send(message)
                    return
                chunks.append(message.get("body", b"") or b"")
                if message.get("more_body"):
                    return
                await _emit(send, state["start"], b"".join(chunks))
            else:
                await send(message)

        await app(scope, receive, _capture)

    return _wrapped


async def _emit(send, start_message, body: bytes):
    new_body = body
    try:
        payload = json.loads(body)
        # JSON-RPC error: {"jsonrpc": "2.0", "error": {"data": [ {...,"input":..}]}}
        data = payload.get("error", {}).get("data")
        if isinstance(data, list) and any(
            isinstance(e, dict) and "input" in e for e in data
        ):
            for e in data:
                if isinstance(e, dict):
                    e.pop("input", None)
            new_body = json.dumps(payload).encode("utf-8")
    except Exception:  # noqa: BLE001 — never let hardening break a response
        new_body = body

    if start_message is not None:
        headers = [
            (k, v)
            for (k, v) in start_message.get("headers", [])
            if k.lower() != b"content-length"
        ]
        headers.append((b"content-length", str(len(new_body)).encode("latin-1")))
        start_message = {**start_message, "headers": headers}
        await send(start_message)
    await send({"type": "http.response.body", "body": new_body, "more_body": False})


if __name__ == "__main__":
    import re
    from pathlib import Path

    import uvicorn
    from bedrock_agentcore.runtime import build_a2a_app

    app = build_a2a_app(executor, agent_card, ping_handler=_ping_status)
    app = _strip_error_input(app)

    # Serve local-storage deliverables at /erc8183/job/{id}/response so that
    # ERC8183_AGENT_URL=http://localhost:9000/erc8183 works in local dev.
    # The LocalStorageProvider writes job-{id}.json into STORAGE_LOCAL_PATH.
    _inner = app
    _storage_dir = Path(os.environ.get("STORAGE_LOCAL_PATH") or ".agent-data")

    async def _app(scope, receive, send):
        if scope["type"] == "http":
            path = scope.get("path", "")
            m = re.match(r"^/erc8183/job/(\d+)/response$", path)
            if m:
                fpath = _storage_dir / f"erc8183-job-{m.group(1)}.json"
                if fpath.exists():
                    body = fpath.read_bytes()
                    await send({"type": "http.response.start", "status": 200,
                                "headers": [(b"content-type", b"application/json"),
                                            (b"content-length", str(len(body)).encode())]})
                    await send({"type": "http.response.body", "body": body})
                else:
                    await send({"type": "http.response.start", "status": 404, "headers": []})
                    await send({"type": "http.response.body", "body": b"not found"})
                return
        await _inner(scope, receive, send)

    # --- x402 / Binance Pay channel -------------------------------------------
    # Mount the x402 handler as the outermost ASGI layer so it intercepts
    # /x402/* before the A2A server, the ERC-8183 local-storage route, and
    # the JSON-RPC error-hardening middleware. Payment verification and SSE
    # streaming are fixed code — the LLM sees only the analysis prompt.
    from x402_handler import X402Handler
    _app = X402Handler(
        _app,
        stream_work=_stream_runner,
        generator=GENERATOR,
    )

    uvicorn.run(
        _app,
        host=os.environ.get("AGENT_BIND_HOST") or "0.0.0.0",
        port=int(os.environ.get("AGENT_PORT") or "9000"),
        log_level="info",
    )
